### ISSUE TITLE
Switch R package that reads excel files from 'xlsx' to 'readxl' to bypass Java dependency?

### ISSUE THREAD

**Issue by evanbooher** [wdfw-fp/CreelScheduleGenerator#2]
The package 'xlsx' requires Java, requiring all users of CreelScheduleGenerator to request a Java license for their work computer. Would the tidyverse package 'readxl' provide the same functionality, minus the Java dependency? @kalebentley 

P.S. 'xlsx' is also used in the CreelAnalysis repo, but the new data ingest from the DB probably bypasses this issue (if I recall correctly that @daauerbach had made some headway getting to the list object for stan from the same data ingest / wrangling used in CreelPointEstimate)

**Comment by kalebentley** [comment]
Looks like the package "openxlsx" is another option for writing Excel files from R (and can accommodate [multiple tab outputs](https://stackoverflow.com/questions/27713310/easy-way-to-export-multiple-data-frame-to-multiple-excel-worksheets))

**Comment by ctholley** [comment]
Changed package used to write out schedule to an Excel file from "xlsx" to "openxlsx" in this commit ba9d5c2c040002280307725a31c27d770616ed17 to avoid a Java software dependency.
